# Spring
spring:
  profiles.active: local
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: true
  messages:
    basename: messages
    encoding: utf-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: web
    password: web
    hikari:
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
# SERVER
server:
  port: 8080
  error:
    whitelabel.enabled: true
    include-exception: true
    include-message: always
    include-stacktrace: always
    include-binding-errors: always
# MyBatis
mybatis:
  type-aliases-package: io.ahakim.crud.domain
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
# SpringDoc
springdoc:
  version: v1
  packages-to-scan: io.ahakim.crud.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs/${springdoc.version}
    groups.enabled: true
  swagger-ui:
    path: /api-docs
    operations-sorter: method
    disable-swagger-default-url: true






